import type { Metadata } from "next";
import { Inter } from 'next/font/google'
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "FlavorTales",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="es">
      <body
        className={inter.className + ' antialiased flex h-screen overflow-hidden'}
      >
        <Providers>
          <Sidebar>
            {children}
          </Sidebar>
        </Providers>
      </body>
    </html>
  );
}
